[server]
port = 8501
address = "localhost"
enableCORS = true
enableXsrfProtection = false
maxUploadSize = 200

[browser]
serverAddress = "localhost"
serverPort = 8501
gatherUsageStats = false

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
